---View Sample Data ---

SELECT * FROM PATIENT.DATA.INFORMATION;

---Total Number of Patients
SELECT COUNT(DISTINCT Patient_ID) AS Total_Patients
FROM PATIENT.DATA.INFORMATION;

---Total Admissions
SELECT COUNT(*) AS Total_Admissions
FROM PATIENT.DATA.INFORMATION;

---Checking Readmission Number
SELECT COUNT(*) AS Total_Readmissions
FROM PATIENT.DATA.INFORMATION

---Checking Age
SELECT
   Age
FROM PATIENT.DATA.INFORMATION 

---Checking DISTINCT Gender
SELECT
   DISTINCT GENDER
FROM PATIENT.DATA.INFORMATION   

---Checking DISTINCT Admission Type
SELECT
  DISTINCT ADMISSION_TYPE
FROM PATIENT.DATA.INFORMATION  

---Checking Previous Admission
SELECT
 COUNT(*) PREVIOUS_ADMISSION
FROM PATIENT.DATA.INFORMATION 

---Checking MAX Age
SELECT 
 MAX(AGE)
 FROM PATIENT.DATA.INFORMATION;

--- checking MIN Age
 SELECT
   MIN(AGE)
 FROM PATIENT.DATA.INFORMATION;

 ---Checking MIN Number of Diagnosis
 SELECT 
  MIN(NUMBER_OF_DIAGNOSES)
 FROM PATIENT.DATA.INFORMATION; 

---Checking MAX Number of Diagnosis 
 SELECT 
  MAX(NUMBER_OF_DIAGNOSES)
 FROM PATIENT.DATA.INFORMATION;

 ---Creating CASE STATEMENT for Number of Diagnosis
 SELECT
    CASE 
      WHEN NUMBER_OF_DIAGNOSES BETWEEN 0 AND 2 THEN '01. 0-2 Minor'
      WHEN NUMBER_OF_DIAGNOSES BETWEEN 3 AND 5 THEN '02.3-5 Normal'
      WHEN NUMBER_OF_DIAGNOSES BETWEEN 6 AND 8 THEN '03. 6-8 High'
      ELSE '04.9+ Severe'
      END AS NUMBER_OF_DIAGNOSES_GROUP
  FROM PATIENT.DATA.INFORMATION;    

  ---Creating CASE STATEMENT for Previous Admission
  SELECT 
     CASE
       WHEN PREVIOUS_ADMISSIONS BETWEEN 0 AND 2 THEN '01. 0-2 Low'
       WHEN PREVIOUS_ADMISSIONS BETWEEN 3 AND 5 THEN '02. 3-5 High'
       ELSE '03.6+ Critical'
       END AS PREVIOUS_ADMISSIONS_DURATION
   FROM PATIENT.DATA.INFORMATION;      
 
---Creating CASE STATEMENT for Blood Pressure
 SELECT
   CASE
     WHEN BLOOD_PRESSURE BETWEEN 0 AND 120 THEN '01. 0-120  Normal'
     WHEN BLOOD_PRESSURE BETWEEN 121 AND 129 THEN '02. 121-129 ELevated'
     WHEN BLOOD_PRESSURE BETWEEN 130 AND 139 THEN '03. 130-139 High'
     WHEN BLOOD_PRESSURE BETWEEN 140 AND 180 THEN '04.140-180 Very High'
     ELSE '0.5 181+ Critical'
     END AS Blood_Pressure_Stage
  FROM PATIENT.DATA.INFORMATION;   

---Creating CASE STATEMENT for Blood Sugar Level  
SELECT
    CASE
      WHEN BLOOD_SUGAR_LEVELS BETWEEN 3.0 AND 4.0 THEN '01. 3.0-4.0 Low'
      WHEN BLOOD_SUGAR_LEVELS BETWEEN 5.0 AND 7.0 THEN '02. 5.0-7.0 Excellent'
      WHEN BLOOD_SUGAR_LEVELS BETWEEN 8.0 AND 11.0 THEN '03. 8.0-11.0 Good'
      ELSE '0.4 12.0+ Very High'
      END AS BLOOD_SUGAR_LEVELS_Status
 FROM PATIENT.DATA.INFORMATION;   

---Creating CASE STATEMENT for Length of Stay 
 SELECT 
    CASE
     WHEN LENGTH_OF_STAY BETWEEN 0 AND 2 THEN '01. 0-2 Short_Stay'
     WHEN LENGTH_OF_STAY BETWEEN 3 AND 7 THEN '02 3-7 Long_Stay'
     ELSE '0.3 8+ OverStay'
     END AS LENGTH_OF_STAY_DURATION
FROM PATIENT.DATA.INFORMATION;


---Creating CASE STATEMENT for Age Group
SELECT
   CASE
      WHEN AGE < 18 THEN '01.0-18 Teenager'
      WHEN AGE BETWEEN 19 AND 30 THEN '02.19-30 Young Adult'
      WHEN AGE BETWEEN 31 AND 49 THEN '03. 31-49 Adult'
      WHEN AGE BETWEEN 50 AND 64 THEN '03. 50-64 Elder'
      ELSE '04.65+ Senior'
      END AS AGE_GROUP
FROM PATIENT.DATA.INFORMATION;

----FINAL TABLE-----

 SELECT
   PATIENT_ID,
   GENDER,
   READMISSION,
   CASE 
      WHEN NUMBER_OF_DIAGNOSES BETWEEN 0 AND 2 THEN '01. 0-2 Minor'
      WHEN NUMBER_OF_DIAGNOSES BETWEEN 3 AND 5 THEN '02. 3-5 Normal'
      WHEN NUMBER_OF_DIAGNOSES BETWEEN 6 AND 8 THEN '03. 6-8 High'
      ELSE '04.9+ Severe'
   END AS NUMBER_OF_DIAGNOSES_GROUP,
   CASE
      WHEN AGE < 18 THEN '01.0-18 Teenager'
      WHEN AGE BETWEEN 19 AND 30 THEN '02. 19-30 Young Adult'
      WHEN AGE BETWEEN 31 AND 49 THEN '03. 31-49 Adult'
      WHEN AGE BETWEEN 50 AND 64 THEN '03. 50-64 Elder'
      ELSE '04.65+ Senior'
   END AS AGE_GROUP,
   CASE
      WHEN PREVIOUS_ADMISSIONS BETWEEN 0 AND 2 THEN '01. 0-2 Low'
      WHEN PREVIOUS_ADMISSIONS BETWEEN 3 AND 5 THEN '02. 3-5 High'
      ELSE '03.6+ Critical'
   END AS PREVIOUS_ADMISSIONS_DURATION,
   CASE
      WHEN BLOOD_PRESSURE BETWEEN 0 AND 120 THEN '01. 0-120 Normal'
      WHEN BLOOD_PRESSURE BETWEEN 121 AND 129 THEN '02. 121-129 Elevated'
      WHEN BLOOD_PRESSURE BETWEEN 130 AND 139 THEN '03. 130-139 High'
      WHEN BLOOD_PRESSURE BETWEEN 140 AND 180 THEN '04. 140-180 Very High'
      ELSE '05.181+ Critical'
   END AS BLOOD_PRESSURE_STAGE,
   CASE
      WHEN BLOOD_SUGAR_LEVELS BETWEEN 3.0 AND 4.0 THEN '01. 3.0-4.0 Low'
      WHEN BLOOD_SUGAR_LEVELS BETWEEN 5.0 AND 7.0 THEN '02. 5.0-7.0 Excellent'
      WHEN BLOOD_SUGAR_LEVELS BETWEEN 8.0 AND 11.0 THEN '03. 8.0-11.0 Good'
      ELSE '04.12.0+ Very High'
   END AS BLOOD_SUGAR_LEVELS_STATUS,
   CASE
      WHEN LENGTH_OF_STAY BETWEEN 0 AND 2 THEN '01. 0-2 Short Stay'
      WHEN LENGTH_OF_STAY BETWEEN 3 AND 7 THEN '02. 3-7 Long Stay'
      ELSE '03.8+ Over Stay'
   END AS LENGTH_OF_STAY_DURATION
FROM PATIENT.DATA.INFORMATION
ORDER BY READMISSION ASC;
